### PR TITLE
Fun cmds

### PR DESCRIPTION
**Pull request by Darkfire126**

### CODE REVIEW

**Comment by dheerajpv** [comment]
Have you tested it? Does it work?

**Comment by Darkfire126** [comment]
yup

**Comment by Darkfire126** [comment]
just burned out bec I don't fell like making a new mongo db

**Comment by dheerajpv** [comment]
yep i just tested it and it works

**Comment by dheerajpv** [comment]
can you switch from using `try` and `catch` to using `.catch()` on the promises, it's cleaner and can be used to show just the image or just the fact if only one request succeeds if we wish

**Comment by Darkfire126** [comment]
ok one second

**Comment by Darkfire126** [comment]
all work
Tested

**Comment by dheerajpv** [comment]
k, ima pull this now

**Pull request merged**
